name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: List files
        run: ls -R

      - name: See mvn version
        run: mvn -version

      - name: Change directory to product
        run: cd product && ls

      - name: Build with Maven
        run: mvn clean install

      - name: Run Acceptance Tests with Cucumber
        run: mvn verify -Dcucumber.options="--plugin pretty"

      - name: Run E2E Tests with RestAssured
        run: mvn verify -Dtest=RestAssuredTest

      - name: Run Scalability Tests with Artillery
        run: |
          npm install -g artillery
          artillery run product/load-tests/smoke-test.yml
