name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cambiar de directorio
        run: cd product && ls

      - name: Maven Build
        working-directory: ./product
        run: mvn clean install

      - name: Test de aceptación
        working-directory: ./product
        run: mvn verify -Dcucumber.options="--plugin pretty"

      - name: Test E2E
        working-directory: ./product
        run: mvn verify -Dtest=e2e.PriceE2ETest
